import 'dart:async';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:firebase_performance/firebase_performance.dart';
import 'package:flutter/foundation.dart';

// Use the generated options at project root (lib/firebase_options.dart)
// Use the resolver for environment-aware selection (may still map to single project)
import 'package:hemoai/firebase/firebase_options_resolver.dart';
import 'package:hemoai/config/environment.dart';

/// A single place to initialise Firebase, Crashlytics and Performance.
///
/// * Tries to initialise using the placeholders in [DefaultFirebaseOptions].
/// * If the placeholders are still present, the method exits silently so the
///   app can continue to run in offline/dev mode.
Future<void> initializeFirebaseTelemetry({bool skipTelemetry = false}) async {
  try {
    // Initialize with generated options for current platform
    final options = FirebaseOptionsResolver.current;
    final app = await Firebase.initializeApp(options: options);
    debugPrint('[Firebase] Initialised app ${app.name} (env=${Env.value})');

    if (!kIsWeb) {
      if (skipTelemetry) {
        // In tests or when explicitly skipped, ensure telemetry is fully disabled
        try {
          await FirebaseCrashlytics.instance
              .setCrashlyticsCollectionEnabled(false);
        } catch (_) {}
        try {
          await FirebasePerformance.instance
              .setPerformanceCollectionEnabled(false);
        } catch (_) {}
        debugPrint('[Firebase] Telemetry skipped (test mode)');
      } else {
        await _configureCrashlytics();
        await _configurePerformance();
      }
    }
  } catch (error, stackTrace) {
    debugPrint('[Firebase] Initialisation failed: $error');
    debugPrintStack(stackTrace: stackTrace);
  }
}

Future<void> _configureCrashlytics() async {
  final crashlytics = FirebaseCrashlytics.instance;

  await crashlytics.setCrashlyticsCollectionEnabled(!kDebugMode);
  // Annotate events with environment
  try {
    await crashlytics.setCustomKey('env', Env.value);
  } catch (_) {}

  // Set global error handlers for production/debug app runs.
  FlutterError.onError = (details) {
    FlutterError.presentError(details);
    crashlytics.recordFlutterFatalError(details);
  };

  PlatformDispatcher.instance.onError = (error, stack) {
    crashlytics.recordError(error, stack, fatal: true);
    return true;
  };

  debugPrint(
    '[Crashlytics] Enabled (debug collection=${kDebugMode ? 'disabled' : 'enabled'}, env=${Env.value})');
}

Future<void> _configurePerformance() async {
  final performance = FirebasePerformance.instance;
  await performance.setPerformanceCollectionEnabled(!kDebugMode);
  debugPrint(
      '[Firebase Performance] Collection ${kDebugMode ? 'disabled' : 'enabled'}');
}

// Removed placeholder detection now that real options are generated by flutterfire_cli.
